/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtrk_pnrs1_ra43_2014_MyNative */

#ifndef _Included_rtrk_pnrs1_ra43_2014_MyNative
#define _Included_rtrk_pnrs1_ra43_2014_MyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtrk_pnrs1_ra43_2014_MyNative
 * Method:    racun
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_rtrk_pnrs1_ra43_12014_MyNative_racun
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
